### ISSUE TITLE
confuse about the code and result 

### ISSUE THREAD

**Issue by fedryane** [GirishKumarDevadiga/MiniProject_Speech_To_Text_Using_MFCC_and_HMM#1]
hello , i tested your code but there's a error in it , i assume the error was in the confusion matrix and classification reports because the value of them was 0 , here of the pics that i have
![asasasas](https://user-images.githubusercontent.com/24633899/123679530-c7cdf600-d871-11eb-8ea8-04e903cfc9eb.jpg)

![Screenshot_1](https://user-images.githubusercontent.com/24633899/123679560-cef50400-d871-11eb-9b2d-7ed31425313a.jpg)

**Comment by GirishKumarDevadiga** [comment]
Please check the label for prediction in confusion matrix, it should be
folder name like 'yes', 'no' , etc.  instead of individual audio.. Also
this code tested for folder structure in linux.. make necessary changes of
windows
